# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - ibmec-ecommerce-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B8EE01E097E94D6791B31BF30EB07DFD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F30CD6CAEF974BF58C0A65322AC0343F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D056DA5A45354CC085D5D91531775AF1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ibmec-ecommerce-app'
          slot-name: 'Production'
          package: '*.jar'

      - name: Download OpenAPI spec file
        run: |
          # Espera alguns segundos para a aplicação iniciar
          echo "Aguardando aplicação iniciar..."
          sleep 60
          # Baixa o arquivo de especificação OpenAPI da sua aplicação
          echo "Tentando baixar especificação OpenAPI..."
          curl -v https://ibmec-ecommerce-app-gydeg9hye0eabpbf.brazilsouth-01.azurewebsites.net/api-docs -o api-spec.json

      - name: Update API Management
        uses: azure/cli@v1
        with:  
          inlineScript: |
            # Importa a especificação para o API Management
            az apim api import \
              --resource-group ibmec-ecommerce-rg \
              --service-name ibmec-mall-api \
              --api-id ibmec-ecommerce \
              --path '/ecommerce' \
              --display-name 'IBMEC E-commerce API' \
              --specification-format OpenApiJson \
              --specification-path api-spec.json \
              --subscription-required false
          
